services:
  postgresql:
    image: "postgres"
    ports:
      - "5432:5432"
    expose:
      - "5432"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=password
      - POSTGRES_USER=gabma
      - POSTGRES_PASSWORD=gabma
      - POSTGRES_DB=marketdb
    volumes:
      - db_data:/var/lib/postgresql
volumes:
  db_data: